Models/ViewModels/Shared/VideoInfo.cs
namespace RanchDuBonheur.Models.ViewModels.Shared
{
    public class VideoInfo
    {
        public Guid Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? YtLink { get; set; }
    }
}

Controllers/SalleController.cs
using Microsoft.AspNetCore.Mvc;

namespace RanchDuBonheur.Controllers
{
    public class SalleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_FooterPartial.cshtml
<!-- _Footer.cshtml -->

    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-between align-items-center"> 
                <div>
                    <span class="privacy">&copy; 2024 - www.ranchdubonheur.fr - <a asp-area="" asp-controller="Home" asp-action="Privacy">Confidentialité</a></span>
                </div>
                <div>
                    <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">
                        <i class="bi bi-person-circle"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ranch du Bonheur de Nivelle</title>
    @if (!string.IsNullOrEmpty(@ViewData["Title"]?.ToString()))
    {
        <meta property="og:title" content="Cliquez ici pour découvrir - @ViewData["Title"] - Ranch du Bonheur de Nivelle" />
    }
    @if (!string.IsNullOrEmpty(ViewData["OG:Description"]?.ToString()))
    {
        <meta property="og:description" content="@ViewData["OG:Description"]" />
    }
    @if (!string.IsNullOrEmpty(ViewData["OG:Image"]?.ToString()))
    {
        <meta property="og:image" content="@ViewData["OG:Image"]" />
    }
    @if (!string.IsNullOrEmpty(ViewData["OG:Url"]?.ToString()))
    {
        <meta property="og:url" content="@ViewData["OG:Url"]" />
    }
    @if (!string.IsNullOrEmpty(ViewData["MetaDescription"]?.ToString()))
    {
        <meta name="description" content="@ViewData["MetaDescription"]" />
    }
    @if (!string.IsNullOrEmpty(ViewData["CanonicalUrl"]?.ToString()))
    {
        <link rel="canonical" href="@ViewData["CanonicalUrl"]" />
    }


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/bootstrap-icons/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    
    <script type="application/ld+json">
        {
          "@@context": "https://schema.org",
          "@@type": "LocalBusiness",
          "name": "Ranch du Bonheur de Nivelle",
          "image": "@ViewData["OG:Image"]",
          "@@id": "https://www.ranchdubonheur.fr/",
          "url": "https://www.ranchdubonheur.fr/",
          "telephone": "+33642858026",
          "address": {
            "@@type": "PostalAddress",
            "streetAddress": "300 Route de Condé",
            "addressLocality": "Nivelle",
            "postalCode": "59230",
            "addressCountry": "FR"
          },
          "geo": {
            "@@type": "GeoCoordinates",
            "latitude": 50.45952414431575,
            "longitude": 3.494811146368993
          },
          "openingHoursSpecification": [
            {
              "@@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Sunday"
              ],
              "opens": "12:30",
              "closes": "21:00"
            }
          ]
        }
    </script>

    <!-- Matomo -->
    <script>
        var _paq = window._paq = window._paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function () {
            var u = "//www.matomo.cedric-caudron.com/";
            _paq.push(['setTrackerUrl', u + 'matomo.php']);
            _paq.push(['setSiteId', '2']);
            var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
            g.async = true; g.src = u + 'matomo.js'; s.parentNode.insertBefore(g, s);
        })();
    </script>
    <!-- End Matomo Code -->
</head>
<body>
    <header>
        <partial name="_NavbarPartial" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_ToastNotifications" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <partial name="_FooterPartial" />
    </footer>

    <!-- Inclusion du bandeau de consentement -->
    <partial name="_CookieConsentPartial" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavbarPartial.cshtml
<!-- _Navbar.cshtml -->
<nav class="navbar navbar-expand-lg navbar-toggleable-lg border-bottom box-shadow mb-3 fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/images/logo/logo.jpg" alt="Le Ranch Du Bonheur Logo" style="height: 50px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item m-2">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                </li>
                <li class="nav-item m-2">
                    <a class="nav-link" asp-area="" asp-controller="Event" asp-action="Index">Dates & Menus</a>
                </li>
                <li class="nav-item m-2">
                    <a class="nav-link" asp-area="" asp-controller="Artists" asp-action="Index">Les Artistes</a>
                </li>
                @* <li class="nav-item m-2">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Salle" asp-action="Index">La Salle</a>
                </li>
                <li class="nav-item m-2">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Informations" asp-action="Index">Infos Utiles</a>
                </li> *@
                @if (User!.Identity!.IsAuthenticated)
                {
                    <li class="nav-item m-2">
                        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="AdminIndex">Administration</a>
                    </li>
                }
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

Views/Shared/_ToastNotifications.cshtml
@{
    var successMessage = TempData["Success"] as string;
    var errorMessage = TempData["Error"] as string;
}

@if (!string.IsNullOrEmpty(successMessage) || !string.IsNullOrEmpty(errorMessage))
{
    <div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">
        <div style="position: absolute; top: 0; right: 0;">

            @if (!string.IsNullOrEmpty(successMessage))
            {
                <div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="5000">
                    <div class="toast-header">
                        <strong class="mr-auto">Succès</strong>
                        <button type="button" class="ml-2 mb-1 close btn-close" data-bs-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="toast-body">
                        @successMessage
                    </div>
                </div>
            }

            @if (!string.IsNullOrEmpty(errorMessage))
            {
                <div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="5000">
                    <div class="toast-header">
                        <strong class="mr-auto">Erreur</strong>
                        <button type="button" class="ml-2 mb-1 close btn-close" data-bs-dismiss="toast" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="toast-body">
                        @errorMessage
                    </div>
                </div>
            }
        </div>
    </div>
}


@section Scripts {
    <script>
        $(document).ready(function () {
            $('.toast').toast('show');
        });
    </script>
}